# Configuration for the cost map. See
# https://wiki.ros.org/navigation/Tutorials/RobotSetup.

# Include objects that are 2.5 meters away in the local cost map.
obstacle_range: 2.5
transform_tolerance: 30
# Raytrace free space to 3 meters. TODO: what does this mean?
raytrace_range: 3.0

# Convex hull of the robot, in meters.
# TODO: Can we get this from the URDF?

footprint: [
  [-0.3, -0.25],
  [0.3, -0.25],
  [0.3, 0.25],
  [-0.3, 0.25]
]

#robot_radius: ir_of_robot
inflation_radius: 0.4

plugins:
  - {name: inflation, type:"costmap_2d::InflationLayer"}
  - {name: obstacle, type:"costmap_2d::ObstacleLayer"}
  - {name: static_layer, type:"costmap_2d::StaticLayer"}

# From https://answers.ros.org/question/293696/move_base-to-use-map-published-on-a-certain-topic/
# plugins:
# dwa_local_planner::DWAPlannerROS
#   - {name: inflation, type:"costmap_2d::InflationLayer"}
#   - {name: static_layer, type:"costmap_2d::StaticLayer"}
