// Structures and conversions generated by can.py.
#ifndef BOWIE_H
#define BOWIE_H
#include <stdint.h>
#include <ostream>
namespace can {

inline uint64_t read(uint64_t &buffer, uint8_t bits) {
  uint64_t res = buffer & ((1 << bits) - 1);
  return buffer >>= bits, res;
}

inline void write(uint64_t &buffer, uint8_t bits, uint64_t data) {
  buffer <<= bits;
  buffer |= data;
}

inline void to_buffer(uint8_t *buffer, uint64_t number) {
  *(uint64_t *)buffer = number;
}

inline uint64_t from_buffer(const uint8_t *buffer) {
  return *(const uint64_t *)buffer;
}

enum class FrameID {
  EStop = 0,
  MotorCommands = 1,
  ActuatorCommands = 2,
  Error = 3,
};

inline bool bool_deserialize(uint64_t buffer) { return buffer; }

inline uint64_t serialize(bool data) { return data; }

struct SingleMotorCommand {
  double speed;
};

inline SingleMotorCommand SingleMotorCommand_deserialize(uint64_t buffer) {
  SingleMotorCommand self;
  self.speed = (double)read(buffer, 16) * 0.03125047684443427 + -1024;
  return self;
}

inline uint64_t serialize(SingleMotorCommand data) {
  uint64_t ser = 0;
  write(ser, 16, (data.speed - -1024) / 0.03125047684443427);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const SingleMotorCommand &self) {
  return os << "{ "
            << "speed = " << self.speed << ", "
            << "}";
}

enum class ErrorCode {
  ActuatorOutOfRange = 0,
};

inline ErrorCode ErrorCode_deserialize(uint64_t buffer) {
  return (ErrorCode)buffer;
}

inline uint64_t serialize(ErrorCode data) {
  return (uint64_t)data;
}

inline std::ostream &operator<<(std::ostream &os, const ErrorCode &self) {
  switch (self) {
  case ErrorCode::ActuatorOutOfRange:
    os << "ErrorCode::ActuatorOutOfRange";
    break;
  }
  return os;
}

struct EStop {
  bool stop;
};

inline EStop EStop_deserialize(uint64_t buffer) {
  EStop self;
  self.stop = bool_deserialize(read(buffer, 1));
  return self;
}

inline uint64_t serialize(EStop data) {
  uint64_t ser = 0;
  write(ser, 1, serialize(data.stop));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const EStop &self) {
  return os << "{ "
            << "stop = " << self.stop << ", "
            << "}";
}

struct MotorCommands {
  SingleMotorCommand left;
  SingleMotorCommand right;
};

inline MotorCommands MotorCommands_deserialize(uint64_t buffer) {
  MotorCommands self;
  self.left = SingleMotorCommand_deserialize(read(buffer, 16));
  self.right = SingleMotorCommand_deserialize(read(buffer, 16));
  return self;
}

inline uint64_t serialize(MotorCommands data) {
  uint64_t ser = 0;
  write(ser, 16, serialize(data.right));
  write(ser, 16, serialize(data.left));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const MotorCommands &self) {
  return os << "{ "
            << "left = " << self.left << ", "
            << "right = " << self.right << ", "
            << "}";
}

struct ActuatorCommands {
  double lifter_pos;
  double bucket_pos;
};

inline ActuatorCommands ActuatorCommands_deserialize(uint64_t buffer) {
  ActuatorCommands self;
  self.lifter_pos = (double)read(buffer, 8) * 0.9803921568627451 + 0;
  self.bucket_pos = (double)read(buffer, 8) * 1.1764705882352942 + 0;
  return self;
}

inline uint64_t serialize(ActuatorCommands data) {
  uint64_t ser = 0;
  write(ser, 8, (data.bucket_pos - 0) / 1.1764705882352942);
  write(ser, 8, (data.lifter_pos - 0) / 0.9803921568627451);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const ActuatorCommands &self) {
  return os << "{ "
            << "lifter_pos = " << self.lifter_pos << ", "
            << "bucket_pos = " << self.bucket_pos << ", "
            << "}";
}

struct Error {
  ErrorCode error_code;
};

inline Error Error_deserialize(uint64_t buffer) {
  Error self;
  self.error_code = ErrorCode_deserialize(read(buffer, 0));
  return self;
}

inline uint64_t serialize(Error data) {
  uint64_t ser = 0;
  write(ser, 0, serialize(data.error_code));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const Error &self) {
  return os << "{ "
            << "error_code = " << self.error_code << ", "
            << "}";
}
} // namespace can_BOWIE
#endif // BOWIE_H
