input_sources:
  d455_r:
    type: pointcloud
    topic: /d455_right/depth/color/points_cropped
    queue_size: 5
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 0.5
  d455_l:
    type: pointcloud
    topic: /d455_left/depth/color/points_cropped
    queue_size: 5
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 0.5

map_frame_id: "map"
robot_base_frame_id: "base_link"

postprocessor_pipeline_name: postprocessor_pipeline
#enable_continuous_cleanup: true
postprocessor_num_threads: 6
enable_visibility_cleanup: false

robot_pose_with_covariance_topic: "/pose_with_covariance"
track_point_frame_id:                       "base_link"
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0

# Map.
length_in_x:                                20.0
length_in_y:                                20.0
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.1
